// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0IiXGpAqPkSEeDIpie7_JGyrp-NLTP4g',
    appId: '1:1091976809370:web:c0fe109678bba6ac534823',
    messagingSenderId: '1091976809370',
    projectId: 'alien-array-302809',
    authDomain: 'alien-array-302809.firebaseapp.com',
    storageBucket: 'alien-array-302809.appspot.com',
    measurementId: 'G-K265GFZJ0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAU53dJRSSHn-RB3ZDx1XWd44F-wN_xAc',
    appId: '1:1091976809370:android:f492378be89864af534823',
    messagingSenderId: '1091976809370',
    projectId: 'alien-array-302809',
    storageBucket: 'alien-array-302809.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcJX6sM9O6T2EpWeFOkeYyT_v_QDWEtM0',
    appId: '1:1091976809370:ios:e192296ca94f3194534823',
    messagingSenderId: '1091976809370',
    projectId: 'alien-array-302809',
    storageBucket: 'alien-array-302809.appspot.com',
    androidClientId:
        '1091976809370-2t0ei5nj3d5qa7gov2ctkcdpjm2r2t6i.apps.googleusercontent.com',
    iosClientId:
        '1091976809370-aefvl3bdgcovm0sie9kb5qn5eaimggko.apps.googleusercontent.com',
    iosBundleId: 'com.umg.coursia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcJX6sM9O6T2EpWeFOkeYyT_v_QDWEtM0',
    appId: '1:1091976809370:ios:69ad570f46feb1cc534823',
    messagingSenderId: '1091976809370',
    projectId: 'alien-array-302809',
    storageBucket: 'alien-array-302809.appspot.com',
    androidClientId:
        '1091976809370-2t0ei5nj3d5qa7gov2ctkcdpjm2r2t6i.apps.googleusercontent.com',
    iosClientId:
        '1091976809370-v5rpmsrf4115vir21vta3db88a277o1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.coursia',
  );
}
